import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from "@/components/providers/theme-provider"

import { ClerkProvider } from '@clerk/nextjs'
import { cn } from '@/lib/utils'

const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'echoLoom',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
      
        <body className={cn(font.className, 
          "bg-white dark:bg-[#313338]"
          )}>
          <ThemeProvider
            attribute="class" 
            defaultTheme="dark"
            enableSystem={false}
            storageKey='echoloom-theme'
          >
            {children}
          </ThemeProvider>

        </body>

      </html>
    </ClerkProvider>

  )
}
